"""Rebase database

Revision ID: bdaa9926f648
Revises: 51501a4f9ada
Create Date: 2025-05-14 17:02:56.747465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdaa9926f648'
down_revision: Union[str, None] = '51501a4f9ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('work_hours', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('0 <= work_hours AND work_hours <= 24', name='check_work_hours_range'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'owner_id', name='unique_date_for_user_manual_days')
    )
    op.create_index(op.f('ix_manual_days_owner_id'), 'manual_days', ['owner_id'], unique=False)
    op.create_index(op.f('ix_days_owner_id'), 'days', ['owner_id'], unique=False)
    op.drop_column('days', 'is_generated')
    op.add_column('task_executions', sa.Column('doing_hours', sa.Integer(), nullable=False))
    op.drop_column('task_executions', 'doing_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_executions', sa.Column('doing_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('task_executions', 'doing_hours')
    op.add_column('days', sa.Column('is_generated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_days_owner_id'), table_name='days')
    op.drop_index(op.f('ix_manual_days_owner_id'), table_name='manual_days')
    op.drop_table('manual_days')
    # ### end Alembic commands ###
