"""Add cascade attributes and passive_deletes for all relationships

Revision ID: da692a350960
Revises: 9393da9873e8
Create Date: 2025-05-15 13:08:17.607037

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'da692a350960'
down_revision: Union[str, None] = '9393da9873e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_failed_tasks_task_id', table_name='failed_tasks')
    op.create_index(op.f('ix_failed_tasks_task_id'), 'failed_tasks', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failed_tasks_task_id'), table_name='failed_tasks')
    op.create_index('ix_failed_tasks_task_id', 'failed_tasks', ['task_id'], unique=False)
    # ### end Alembic commands ###
