"""Add relationship manual_days to User

Revision ID: 9393da9873e8
Revises: bdaa9926f648
Create Date: 2025-05-14 17:08:37.350570

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '9393da9873e8'
down_revision: Union[str, None] = 'bdaa9926f648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
